### ISSUE TITLE
Rsync error during production.

### ISSUE THREAD

**Issue by krisMoca** [doublesecretagency/craft-googlemaps#63] opened 2022-08-08 23:10 UTC
We are having this rsync error when pushing our  code base to our production server.
![image](https://user-images.githubusercontent.com/86084360/183529475-50a34710-90bd-4999-abbe-26c0f5e7a95f.png)

trying to open the file locally and it showing a FileSystemError message.
![image](https://user-images.githubusercontent.com/86084360/183529598-19bac2dc-4a9a-4ac2-9902-b95965495caa.png)

![image](https://user-images.githubusercontent.com/86084360/183529673-61c7f36f-43c0-491c-bad0-a44823085312.png)

What's the best way to solve this issue?

**Comment by lindseydiloreto** [comment] 2022-08-09 06:07
Well that's... interesting. Looks like a relic from my attempt to implement Codeception. You'll notice I didn't get very far.

That particular file is a **symlink**. But it's not being used at all, so it's probably safe to just delete it. Go into the `vendor` folder and just delete it for now. Once you've deleted the file, I believe `rsync` should work as intended.

I'll circle back soon and remove it from the repo. That symlink isn't currently serving a purpose, I may as well delete it until I'm ready to give Codeception another shot.

**Comment by lindseydiloreto** [comment] 2022-10-16 05:46
This symlink has been removed. The fix will be included in the next release (v4.2.6).

Thanks for reporting it! 👍

**Closed as completed by lindseydiloreto** 2022-10-16 05:46 UTC
Labels: Bug Report

**Comment by justinmacleod** [comment] 2023-01-15 18:40
@lindseydiloreto We just encountered this issue with a CodeDeploy deployment using your plugin. I see that 4.2.6 hasn't been tagged yet. Can you tag that release so we can properly upgrade? For now, I'll exclude the file when pushing to CodeDeploy. Thanks!

**Comment by lindseydiloreto** [comment] 2023-01-16 06:04
Hi @justinmacleod,

That release is still waiting for a few other things to be completed. To get the latest dev version (including the fix for this ticket), just change the composer package version to this...

```js
"doublesecretagency/craft-googlemaps": "dev-v4-dev"
```

... then run `composer update`.

Hope that helps!

**Comment by lindseydiloreto** [comment] 2023-02-02 21:22
This fix has been officially released in **v4.3**. 👍
