### ISSUE TITLE
Updating from 4.2.5 -> 4.3.0 causes db error. 

### ISSUE THREAD

**Issue by delux589** [doublesecretagency/craft-googlemaps#84] opened 2023-05-22 16:39 UTC
We are trying to update all our craft plugins and we are hitting a problem when updating this plugin. 

We are currently on version 4.2.5 but when updating to the latest version we then get a missing db column as in the screenshot below. 

<img width="926" alt="Screenshot 2023-05-22 at 13 14 59" src="https://github.com/doublesecretagency/craft-googlemaps/assets/102749897/08240c9a-4234-4b06-8213-8bbf0cfcb33a">

this seems to be an issue after [this migration](https://github.com/doublesecretagency/craft-googlemaps/blob/v4-dev/src/migrations/m221125_125701_update_subfield_config.php) has run when updating to the next available version which is 4.3.0 from our current version. 

We have also tried updating all the way to 4.3.3 and the issue persists. 

We are on the latest craft version. 

I hope this helps.

**Comment by lindseydiloreto** [comment] 2023-06-02 20:37
Hi @delux589, it's hard to say what the issue is here. Nothing in that stack trace is explicitly pointing at the Google Maps plugin.

Did you have to restart the update process at some point? If so, did you completely rollback the database first? It almost sounds like the system is trying to run an update after a previously failed migration.

The stack trace indicates that the process moves through your `sitemodule` module, specifically `ImportFormattingService.php`. You may want to check the custom code you have in there.

If you're confident that this is an issue with the Google Maps plugin, feel free to hit me up on Discord and I can help you work through it.

**Comment by lindseydiloreto** [comment] 2023-06-09 17:15
Closing this thread, but feel free to ping me on Discord if you think you're still having a Google Maps issue. 👍

**Closed as completed by lindseydiloreto** 2023-06-09 17:15 UTC

**Comment by Kingo4luv** [comment] 2023-06-12 13:45
Hi @lindseydiloreto 

 I am following up on a previously closed issue (Issue #84) reported by my colleague. We are still encountering difficulties when updating the Google Maps plugin from version 4.2.5 to 4.3.0​[1](https://github.com/doublesecretagency/craft-googlemaps/issues/84)​.

Based on our investigations, it appears that the migration associated with this update is causing a column (field_address) to be removed from the database. This seems to be the root cause of the error we are facing, as this column is required by our system.

Our findings are based on the following steps:

- We restored our database to the state it was in before the update attempt.
- We noted the structure of the database, specifically the columns present in the content table.
- We then proceeded to update the Google Maps plugin and run the migration that comes with it.
- After the migration, we observed that the field_address column was no longer present in the content table.

The error message we encounter when trying to use the system after the update specifically mentions the absence of the field_address column​.

We wanted to bring this to your attention as this might be an unintended side effect of the migration process. Any guidance on how to address this issue would be greatly appreciated.

**Comment by lindseydiloreto** [comment] 2023-06-12 22:58
Hi @Kingo4luv, happy to help. Would you mind pinging me on Discord (lindseydiloreto#3339) so we can go into greater detail about your migration issue?

For various reasons (including complexity and security), it is much easier to troubleshoot migration issues via Discord.
